# Generated by Django 4.1.7 on 2023-03-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/profile_default.jpg', null=True, upload_to='profile_pictures/'),
        ),
    ]
