# Generated by Django 4.1.7 on 2023-04-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_is_student_remove_user_is_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default='default', max_length=150),
            preserve_default=False,
        ),
    ]
