version: "3.9"

services:
  db:
    image: postgres
    environment:
     - POSTGRES_DB=postgres
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  web:
    build: .
    command: bash -c "while !</dev/tcp/db/5432; do sleep 1; done &&
     python manage.py migrate &&
     python manage.py loaddata fixtures/data.json &&
     python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code/
    ports:
      - "8000:8000"
    depends_on:
      - db
    stdin_open: true
    tty: true
