# Generated by Django 4.1.7 on 2023-04-25 20:07

from django.db import migrations
import learning.fields


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_rename_discription_module_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='content',
            name='order',
            field=learning.fields.OrderField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='order',
            field=learning.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
